### ISSUE TITLE
Missing assets?

### ISSUE THREAD

**Issue by miyu** [achlubek/venginenative#4]
Hey, finally got this compiling (I think?)!
Getting "File fresnel.png not found in media map". 

Commented these lines to move forward:
```
fresnelTexture = new Texture2d("fresnel.png");
starsTexture = new Texture2d("stars.png");
moonTexture = new Texture2d("moon.png");
```

Then getting Intelfile sp.scene not found in media map.

Are these provided somewhere?

**Comment by achlubek** [comment]
Hi, i will pack media and send it to you, meanwhile uncomment that fresnel
textures because those are important.

16.05.2017 10:41 AM "Michael Yu" <notifications@github.com> napisał(a):

**Comment by miyu** [comment]
Fantastic. Also getting these when I disable the scene load, though perhaps I just need the media files?

```
VERSION: 4.4.0 - Build 20.19.15.4463
VENDOR: IntelCompiling shader Generic.vertex.glsl
COMPILATION FAILED WITH MESSAGE::
ERROR: 0:52: '' : member array requires size
ERROR: 0:56: '' : member array requires size


Compiling shader Material.fragment.glsl
AL lib: (EE) MMDevApiMsgProc: Unexpected message: 49373
LINKING FAILED WITH MESSAGE::
Fragment shader contains a user varying, but is linked without a vertex shader.
Out of resource error.

Compiling shader Generic.vertex.glsl
```

**Comment by achlubek** [comment]
You will need to fix shaders on your own because I dont have other gpus for testing, Also its incompatible with intels. If you want materials link you can provide me some email address so I can send link, I cant publish that on github because of various licenses
